// ShapeScript document

detail 190

define RADIUSBOTTOM    94
define RADIUSTOP       104.8
define HEIGHT          64
define DEPTH           (HEIGHT / 2)
define THICKNESS       (RADIUSBOTTOM / 10)
define WALLTHICKNESS   1
define DIAMETER        (THICKNESS * (pi / 2) - WALLTHICKNESS * 2)

difference {
    lathe path {
        point 0 HEIGHT
        point (RADIUSTOP / 2 + THICKNESS)  HEIGHT
        point (RADIUSBOTTOM / 2 + THICKNESS)  0
        point 0  0
    }

    cube {
        size (RADIUSTOP + THICKNESS * 2 + WALLTHICKNESS)  (HEIGHT - DEPTH)  (RADIUSTOP + THICKNESS * 2 + WALLTHICKNESS)
        position 0  ((HEIGHT + DIAMETER) - ((HEIGHT - DEPTH) / 2))
    }

    cone {
        orientation 1
        size (RADIUSTOP + THICKNESS * 2 + WALLTHICKNESS * 2)  (THICKNESS * 2)
        position 0  (HEIGHT / 2 + THICKNESS / 2)
    }
}
