name: build

on:
  push:
  pull_request:
jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        swiftver:
          - swift:5.2
          - swiftlang/swift:nightly-main
        swiftos:
          - focal
    runs-on: ubuntu-latest
    container:
      image: ${{ format('{0}-{1}', matrix.swiftver, matrix.swiftos) }}
      options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --security-opt apparmor=unconfined
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery
